### ISSUE TITLE
CLI not working

### ISSUE THREAD

**Issue by devinellis** [a-type/lo-fi#179]
Hi,

I wanted to test out lo-fi as I think your approach sounds very reasonable. However, I can't get past the schema generation step. I get this error, with or without the parameters:

```
$ npx lo-fi
/usr/local/bin/lo-fi: 1: import: not found
/usr/local/bin/lo-fi: 2: import: not found
/usr/local/bin/lo-fi: 3: import: not found
/usr/local/bin/lo-fi: 4: import: not found
/usr/local/bin/lo-fi: 5: import: not found
/usr/local/bin/lo-fi: 6: import: not found
/usr/local/bin/lo-fi: 7: getAllCollectionDefinitions,: not found
/usr/local/bin/lo-fi: 8: getCollectionTypings,: not found
/usr/local/bin/lo-fi: 9: Syntax error: "}" unexpected
```

This is within a node:18 docker image (BTW, I had to downgrade from node 19 to 18 because better-sqlite3@7 was failing to build)

**Comment by a-type** [comment]
Ah, that's honestly not surprising. This looks to me like you're not running in an ESM environment. Possibly changing the root `package.json` to `"type": "module"` would fix it.

For better or worse (mostly worse lol) I chose to go all-in with ESM for this project from the start. I was betting on ESM seeing more adoption soon, but it's seeming like it's going to be a long and messy change...

**Comment by devinellis** [comment]
Ok, I found @lo-fi/create-app and tried tried to run the bin defined in its package.json, but had the same problem.

FWIW, my original project is also set up as "type": "module". 

I will see about running the create-app project directly.

**Comment by a-type** [comment]
Huh, are you just using the base Node 18 docker container? I can try to reproduce and debug further.

**Comment by devinellis** [comment]
Yeah, here's repo steps:
```
% docker run -it node:18 bash
root@f31278ac8fd4:/# npm create @lo-fi/app
Need to install the following packages:
  @lo-fi/create-app@0.1.0
Ok to proceed? (y) y
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/346.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/346.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/346.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/346.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/346.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/346.
/root/.npm/_npx/281c6846e6c2a01b/node_modules/.bin/create-app: 7: Syntax error: "(" unexpected

**Comment by a-type** [comment]
Ouch, I forgot to add the shebang to the script. I guess `npm` needs that, when `pnpm` was working for me.

As a warning though, you'll have to `npm i -g pnpm` before running it.

**Comment by a-type** [comment]
Someday maybe I can expand the kit to use `npm` instead of `pnpm`, but it relies a lot on pnpm's workspace features at the moment.

**Comment by a-type** [comment]
Also I bet your original problem was also a lack of shebang on the script. I'll fix that in the lo-fi CLI and make a release, then you don't have to worry about the create-app.

**Comment by a-type** [comment]
New CLI is building and should release soon. Update your `@lo-fi/cli` to generate your client as in the original issue comment!

https://github.com/a-type/lo-fi/pull/180

**Comment by devinellis** [comment]
That worked, thanks.

**Comment by a-type** [comment]
Great! I'm sure there will be more hiccups as you go, I've not really used lo-fi outside of my own pnpm/ESM project setups. As long as you have the patience, please feel free to keep posting issues and I'll do my best to look into them!

Thanks for trying it!
